### ISSUE TITLE
the 'hi clear' lines wipe syntax when you change files

### ISSUE THREAD

**Issue by alok** [ishan9299/nvim-solarized-lua#10]
removing them fixes the colorscheme resetting issue i mentioned.

**Comment by ishan9299** [comment]
![Screenshot from 2021-04-13 09-17-35](https://user-images.githubusercontent.com/47824004/114494048-43d47c80-9c39-11eb-8cb8-25a4712b21b5.png)
If I remove the `cmd('hi clear')`  in highlights.lua file switching between dark and light themes cause issues.
