### ISSUE TITLE
Inverted borders with FTerm and SnipRun

### ISSUE THREAD

**Issue by maxigaz** [ishan9299/nvim-solarized-lua#12]
In Neovim v0.5.0-dev+1318-g61aefaf29, using the `solarized` variant of this theme, the borders become inverted while using FTerm and SnipRun.

At the beginning, I didn't know where to report this because I also noticed this behaviour in older, built-in colorschemes, so I opened an issue with screenshots and steps to reproduce for [FTerm](https://github.com/numToStr/FTerm.nvim/issues/19) and later for [SnipRun](https://github.com/michaelb/sniprun/issues/80).

**Comment by ishan9299** [comment]
I will look into it thanks.

**Comment by ishan9299** [comment]
Made some changes with the commit 526939389db64ce818642e3e52641f8276ed7470. Can you take a look into it.

**Comment by maxigaz** [comment]
The borders in those two plugins now look good, as well as borders between splits in general. (I thought this latter was a "feature", so I didn't mention it. But I like it better now.)

Thank you very much!
