### ISSUE TITLE
Reducing the visibility of whitespace characters

### ISSUE THREAD

**Issue by maxigaz** [ishan9299/nvim-solarized-lua#13]
Using Neovim v0.5.0-dev+1318-g61aefaf29, I would like to darken whitespace characters using the `solarized` variant, but I don't know how to do that.

I used a minimal `init.test.vim` for reproducing it (by running `nvim -u ~/.config/nvim/init.test.vim --noplugin init.test.vim`) with the following content:

```vim
" Load plugin
let $PLUGIN_DIRECTORY = '~/.local/share/nvim/plugtest'
set runtimepath^=$PLUGIN_DIRECTORY/indent-blankline.nvim

" Initialize
set termguicolors
colorscheme solarized

" Whitespace
set list
lua vim.g.solarized_visibility = 'low'
highlight Whitespace guifg=black

" Test area
" trailing space                          
" trailing tabs					
```

Screenshots (notice how `vim.g.solarized_visibility = 'low'` is actually much brighter than `normal`):

![nvim-solarized-low](https://user-images.githubusercontent.com/10419911/118515352-9a9c0d00-b735-11eb-8be4-98d6c2626366.png)
![nvim-solarized-normal](https://user-images.githubusercontent.com/10419911/118515371-9e2f9400-b735-11eb-87ee-6b9dc3d9d342.png)
![nvim-solarized-high](https://user-images.githubusercontent.com/10419911/118515385-a1c31b00-b735-11eb-8cab-22b6d8f8176c.png)

Another thing to note is that `highlight Whitespace guifg=black` doesn't seem to do anything, only if I `:source` the init file while Neovim is already running.

**Comment by ishan9299** [comment]
Also try setting the option before applying the colorscheme.

**Comment by maxigaz** [comment]
> try setting the option before applying the colorscheme.

OK, I've just tried this:

```vim
set termguicolors

" Whitespace
set list
lua vim.g.solarized_visibility = 'low'
highlight Whitespace guifg=black

" Initialize
colorscheme solarized
```

Now the highlight command doesn't work either, not even after sourcing the init file. Other than that, same results.

> can you try the option NonText instead of WhiteSpace ?

It doesn't seem to make any difference.

**Comment by ishan9299** [comment]
Yup I tried it myself. Thanks for reporting a bug.

**Comment by ishan9299** [comment]
In the mean time can you put this command
```
hi NonText guifg=#657b83 guibg=NONE gui=bold cterm=bold
```
to get low visibility.

**Comment by ishan9299** [comment]
I have made some changes can you check if those work for you?

**Comment by maxigaz** [comment]
It's definitely better, although I would like it to be slightly *brighter* this time.

For example, here's how it looks with `hi NonText guifg=#25454D guibg=NONE gui=bold cterm=bold` applied (which still doesn't work unless I manually run `:source %`, by the way). I would like having this one.

![nvim-solarized-whitespace-low](https://user-images.githubusercontent.com/10419911/118719228-7e2ccd00-b828-11eb-8a8c-bf3002a01e26.png)

**Comment by ishan9299** [comment]
the default option would suit your needs then. Try 'normal' instead of 'low'. I have my config written in lua so in my config.
```
vim.g.solarized_statusline = 'flat'
vim.g.solarized_termtrans = 0
vim.g.solarized_diffmode = 'low'
vim.g.solarized_visibility = 'low'
vim.cmd('colorscheme solarized')
vim.cmd('hi NonText guifg=#25454D guibg=NONE gui=bold cterm=bold')
```
This works fine on my neovim. You can try this in vimscript if it doesn't work then I guess it is a neovim issue not a colorscheme one.

**Comment by ishan9299** [comment]
Also can try to put your settings in ~/.config/nvim/after/syntax?

**Comment by maxigaz** [comment]
> the default option would suit your needs then. Try 'normal' instead of 'low'.

I already have. Something between normal and low would be the ideal choice for me, like what I mentioned above. (Although if you only want to use the base colours defined in Solarized, that's also understandable.)

> I have my config written in lua so in my config.

> 
> ```
> vim.g.solarized_statusline = 'flat'
> vim.g.solarized_termtrans = 0
> vim.g.solarized_diffmode = 'low'
> vim.g.solarized_visibility = 'low'
> vim.cmd('colorscheme solarized')
> vim.cmd('hi NonText guifg=#25454D guibg=NONE gui=bold cterm=bold')
> ```

I've put it into `init.test.lua`, made some modifications, and run `nvim -u ~/.config/nvim/init.test.lua --noplugin init.test.lua`. Here are the results:

![nvim-solarized-lua](https://user-images.githubusercontent.com/10419911/118804962-a575af80-b8a5-11eb-8254-2b26cfd7959a.png)

> I looked up the problem you are having with 'hi' command is an issue with vim too. The only solution I read was that you have to write your own colorscheme. It is weird because the above lua snippet from my config works.
So there is nothing I can do about the `hi` command issue atleast for now.

Oh… so, I guess I'll have to edit the files of nvim-solarized-lua and hardcode the values myself (or make do with the default options). Not exactly what I was looking for, but at least I feel I'm closer now, so, thank you!

**Comment by ishan9299** [comment]
@maxigaz you can try something like this modify the colorscheme.
https://github.com/kristijanhusak/neovim-config/blob/cf911f5feeecdc7acf513714b48c4fcf985eeaf9/nvim/partials/colorscheme.vim#L1

**Comment by maxigaz** [comment]
Thank you for the advice! I'm not very familiar with creating and using `augroup`s, but I've just tried the following `autocmd`s, and they seem to work well (replacing `Whitespace` with `NonText` has the same results for me).

```
vim.cmd([[
autocmd BufEnter * hi Whitespace guifg=#25454D guibg=NONE gui=bold cterm=bold
autocmd BufEnter * hi IndentBlanklineChar guifg=#25454D gui=nocombine
]])
```

The second one using the highlight group `IndentBlanklineChar` was necessary for customising the looks of [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim). It's yet another mystery, because according to the plugin's manual, it "takes guifg color from 'Whitespace'" by default, so, if I understand it well, `hi IndentBlanklineChar` should be redundant. But anyway, I'm happy that it works finally.

Thank you again!
