### ISSUE TITLE
Drastic slowdown when using this color scheme

### ISSUE THREAD

**Issue by tjysdsg** [ishan9299/nvim-solarized-lua#14]
I was using this on a remote server, and it was terribly laggy. By disabling this color scheme nvim became much snappier

**Comment by ishan9299** [comment]
I would have to look into it. Can you give a more detailed log. You can use this as a reference https://vi.stackexchange.com/questions/276/how-to-find-what-slows-down-vim

**Comment by tjysdsg** [comment]
Actually, I found out that other color schemes also slows vim down, I still don't know why, but it's probably not because of 
nvim-solarized-lua

sorry for the trouble, I'll be looking into this...
