### ISSUE TITLE
Missing terminal colors

### ISSUE THREAD

**Issue by lcrockett** [ishan9299/nvim-solarized-lua#15]
Cheers on the colorscheme ! I've noticed colour differences between terminals initiated from within Neovim relative to a regular terminal. I think it's because of missing `terminal_color_` definitions in the colour scheme. Would you be interested in adding these ?

**Comment by ishan9299** [comment]
What variant of solarized are you using for neovim? The theme has different variants which will differ from a normal solarized theme generally provided by terminals.

**Comment by lcrockett** [comment]
I'm using the `normal` variant. Most likely we're missing terminal colours as defined (per example) here: [https://github.com/lifepillar/vim-solarized8/blob/28b81a4263054f9584a98f94cca3e42815d44725/colors/solarized8.vim#L53-L68](https://github.com/lifepillar/vim-solarized8/blob/28b81a4263054f9584a98f94cca3e42815d44725/colors/solarized8.vim#L53-L68)

**Comment by ishan9299** [comment]
yup it is missing I will add that.

**Comment by ishan9299** [comment]
I have added some highlights in 1bd8e57cc6ec4df62096bb42668ff38f993b93e0. Can you check it out.
If it works don't close the issue because I need add it for other variants.

**Comment by lcrockett** [comment]
Perfect, this works wonders. See screenshot (2x NVIM, one with your change, one without, opening tig in `:Terminal`; left is bad, right is good.

![image](https://user-images.githubusercontent.com/58056722/122679670-1503f500-d1ec-11eb-889d-46c87d04c622.png)

Another screenshot of a regular terminal for comparison:

![image](https://user-images.githubusercontent.com/58056722/122679747-572d3680-d1ec-11eb-89cc-2ddcfd53c62e.png)

Cheers mate !

**Comment by ishan9299** [comment]
76c007d105062e57e7afb8a5d05fc8858092706a
