### ISSUE TITLE
Dark background on errors difficult to read

### ISSUE THREAD

**Issue by tissieres** [ishan9299/nvim-solarized-lua#16]
Hello,
Thanks for the plugin first!
I'm using the solarized-normal scheme with light background and find some highlighted characters hard to read like this in markdown for example:
![last](https://user-images.githubusercontent.com/2410978/122873011-91542080-d331-11eb-91fc-98be8114ddb4.png)
I cannot determine what to change.

**Comment by tissieres** [comment]
OK nevermind, its the Error highlighting.

**Comment by tissieres** [comment]
Finally it looks like there is typo here:
https://github.com/ishan9299/nvim-solarized-lua/blob/d74d3b88a3955d56aa1e64a69af3ecaff3ed5252/lua/solarized/solarized-normal/highlights.lua#L134

**Comment by ishan9299** [comment]
can you check it out now?

**Comment by tissieres** [comment]
Much better, thanks. `ErrorMsg` should probably be fixed accordingly, based on vim-solarized8.

**Comment by ishan9299** [comment]
done

**Comment by tissieres** [comment]
Well done, thanks @ishan9299
