### ISSUE TITLE
Differences in ruby with solarized8

### ISSUE THREAD

**Issue by dgmora** [ishan9299/nvim-solarized-lua#19]
Hi, I've noticed some differences between nvim-solarized-lua (flat) and solarized8 (or the original solarized)

nvim-solarized-lua
<img width="409" alt="Screenshot 2021-07-07 at 17 15 17" src="https://user-images.githubusercontent.com/3609616/124785156-e8b7da80-df46-11eb-8a29-9abb52530add.png">

and solarized8
<img width="423" alt="Screenshot 2021-07-07 at 17 14 58" src="https://user-images.githubusercontent.com/3609616/124785486-2ddc0c80-df47-11eb-890b-9d3209def91c.png">

Here's a reference of how the original solarized looks like (there are no symbols, but it's should look like a string): 
![](https://raw.githubusercontent.com/altercation/solarized/master/img/screen-ruby-dark.png)

The main thing is that having symbols rendered as a type make it a bit hard to read (and different from the original).

There are other two differences, but for me they don't change much: The def/end color and `true` being different from a string.

**Comment by ishan9299** [comment]
Sorry for the late reply but what filetype are the first two screenshots from? I need to know so that I can figure out the highlight groups.

**Comment by ishan9299** [comment]
never mind I figured it out.
