### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kabo** [ishan9299/nvim-solarized-lua#20]
What license is this released under please?

**Comment by ishan9299** [comment]
I haven't licensed it. Is it necessary? you can use it for whatever you want to.

**Comment by luator** [comment]
It is necessary as without a license, we are legally not allowed to use it at all. See [here](https://choosealicense.com/no-permission/) for more information.

In practice this is probably not so much of a problem as long as you are not planning to sue us :).  However, it would still be nice to add a license to clarify things and give people some assurance.  If you don't know which license to use, this site may help: https://choosealicense.com
For the "use it for whatever you want" case I would suggest the MIT licence which is very simple and allows basically everything.

**Comment by ishan9299** [comment]
Added a MIT License.
