### ISSUE TITLE
missing colors/*.vim files in master

### ISSUE THREAD

**Issue by markwellis** [ishan9299/nvim-solarized-lua#22]
in commit 0a076f8 the .vim files in `colors/` were removed.

When I tried to use master I got the error `E185: Cannot find color scheme 'solarized'`

If I use commit aae6d8d1 then it works as expected

Was this intentional? Am I doing something wrong?

my init.lua
```
require('packer').startup(function()
    use 'wbthomason/packer.nvim' -- Packer can manage itself
    use "ishan9299/nvim-solarized-lua"
end)

vim.opt.termguicolors = true
vim.opt.background = "dark"
vim.cmd("colorscheme solarized")
```

**Comment by ishan9299** [comment]
what neovim version are you using?

**Comment by ishan9299** [comment]
the neovim 0.5 can load *.lua files from colors/ and other runtime folders

**Comment by markwellis** [comment]
🤦‍♂️ my bad, I was using an old neovim 0.5 nightly!

Sorry, and thanks very much :)
