### ISSUE TITLE
Cannot find color sheme solarized

### ISSUE THREAD

**Issue by smichaud** [ishan9299/nvim-solarized-lua#23]
I updated my plugins and it suddenly stopped working.
I get the following error when starting neovim: `Cannot find color scheme 'solarized'`.
Other colorscheme works properly.

**Comment by ishan9299** [comment]
What version of neovim are you using?  This might be because your neovim version  is too old.

**Comment by smichaud** [comment]
Hi, thank for the quick answer. Here is my version
```
NVIM v0.5.0-dev+1385-g93f15db5d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az139-167

Features: +acl +iconv +tui
```

It was working yesterday, but I updated both my system and my neovim plugins.

**Comment by ishan9299** [comment]
I think try updating your neovim. It still says 0.5-dev it should be 0.6-dev if you are following the master branch or update to the new stable neovim (0.5 is the new stable now) 😀.

**Comment by smichaud** [comment]
Nice, I assumed that my neovim was update, which is not the case. 
It works ! Solarized ftw :)

Thank you
