### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by thmxv** [ishan9299/nvim-solarized-lua#24]
I have this error message when starting neovim under windows with this pluggin enabled:

```
E5113: Error while calling lua chunk: ...led-packages\opt\nvim-solarized-lua\colors\solarized.lua:1: module 'solarized.solarized-normal.highlights' not found:
        no field package.preload['solarized.solarized-normal.highlights']
        no file '.\solarized\solarized-normal\highlights.lua'
        no file 'C:\tools\neovim\Neovim\bin\lua\solarized\solarized-normal\highlights.lua'
        no file 'C:\tools\neovim\Neovim\bin\lua\solarized\solarized-normal\highlights\init.lua'
        no file '.\solarized\solarized-normal\highlights.dll'
        no file 'C:\tools\neovim\Neovim\bin\solarized\solarized-normal\highlights.dll'
        no file 'C:\tools\neovim\Neovim\bin\loadall.dll'
        no file '.\solarized.dll'
        no file 'C:\tools\neovim\Neovim\bin\solarized.dll'
        no file 'C:\tools\neovim\Neovim\bin\loadall.dll'
```

**Comment by ishan9299** [comment]
I am using it just fine on windows.
![image](https://user-images.githubusercontent.com/47824004/125741063-e5eb7c20-c82b-4a44-b81b-d14aeacb250e.png)

**Comment by ishan9299** [comment]
what is location where the plugin is installed. Also what neovim version are you running?

**Comment by thmxv** [comment]
Sorry for the wrong title. The issue must be local to me :(

I am using neovim 0.5.
The plugin is "installed" in ~/.vim/pack/installed-packages/opt  as a git submodule and enabled with "packadd nvim-solarized-lua" in my vimrc.

**Comment by thmxv** [comment]
I investigated a bit and the issue is due to my config files. With all the vim and lua file sourcing each other trying to get a config somewhat still compatible with regular vim I made the mistake to set the color theme before enabling the plugin. The question is more: How did it work on Linux?

Anyway, I am really sorry for the noise and inconvenience. Thank you for the feedback.
