### ISSUE TITLE
All highlights, almost no normal text with TreeSitter highlights

### ISSUE THREAD

**Issue by thmxv** [ishan9299/nvim-solarized-lua#26]
When enabling tree-sitter highlights, almost all the code gets highlighted (mostly blue) and only the `;` stays in the normal text color. I joined a screenshot of lua code, but it is the same with python (almost all in blue) and for `.vim` files it is mostly orange/yellow but still almost nothing in the normal color. 

![Screenshot from 2021-08-02 15-48-22](https://user-images.githubusercontent.com/948798/127911901-5a19f36e-cc67-4771-acd8-2e442e7746eb.png)

**Comment by jeanlucthumm** [comment]
Same issue here;

![image](https://user-images.githubusercontent.com/4934853/129473322-e4b41381-c53e-4d89-82ae-98e1be293845.png)

**Comment by carlsmedstad** [comment]
I have the same issue.

**Comment by tubbo** [comment]
Yeah for some reason this color scheme makes TypeScript look like absolute trash.

This plugin + tree-sitter:

![solarized + tree-sitter](https://i.imgur.com/82I8mxz.png)

Regular Vim's NeoSolarized on its own:

![neosolarized](https://i.imgur.com/3UfDbP7.png)

**Comment by zhaogangang** [comment]
i hava the same problem

**Comment by zhaogangang** [comment]
f found is "set termguicolors" in init.vim, treesitter hight is not word

**Comment by ishan9299** [comment]
@thmxv should be fixed now.

**Comment by thmxv** [comment]
No, still wall of blue with a bit of orange and still close to nothing in the normal foreground color, for pretty much all the programming  language I use. The only thing I can see different is the variables in lua. 

Maybe this is a defect of treestiter or the base solarized theme that just go overboard and cannot decide on what  to (not) highlight.

**Comment by ishan9299** [comment]
@thmxv Previously I made only the luaTSVariable as normal. Now I have made TSVariable as Normal can you now?

**Comment by thmxv** [comment]
It is much better now.

**Comment by ishan9299** [comment]
If any more changes are needed please do tell. Closing for now.

**Comment by folago** [comment]
I still have the wall of blue/green in Golang as the two top screenshots.
And imports and parenthesis are red.
If I can provide more information to fix this let me know.
![image](https://user-images.githubusercontent.com/986630/145719421-e1637b97-199b-4954-adf9-67d5aa947b8e.png)
