### ISSUE TITLE
Information required: how to setup plugin using packer

### ISSUE THREAD

**Issue by idanko** [ishan9299/nvim-solarized-lua#29]
Hello, and thank you for your contribution. I have a question (comes from the issue I've faced). How to setup/configure the plugin using [packer](https://github.com/wbthomason/packer.nvim) properly? My issue is that I couldn't specify plugin options, such as, vim.g.solarized_italics, vim.g.solarized_termtrans and so on. Even default option for italic font doesn't work for me.

After nvim has loaded the values are set to the options correctly, but it's probably performed **after** the color scheme has loaded. With tradition color scheme plugins (not lua) I didn't see such an issue. May you @ishan9299 pls a bit elaborate in this regard?

**Comment by ishan9299** [comment]
I am not familiar with packer. I don't use it but after a quick glance at README you can try this. As far as Italics are considered make sure that the font you are using has a italic font variant.

```
use 'ishan9299/nvim-solarized-lua'
-- your settings here
vim.g.solarized_italics = 1
vim.g.solarized_diffmode = 'normal'
vim.cmd('colorscheme solarized')
```

Also you need to make sure that the options are set before setting the colorscheme.

**Comment by idanko** [comment]
of cause, that snippet straight from my setup, but it doesn't work for me

**Comment by idanko** [comment]
OK, It's a setup issue, here is minimal setup which works as expected:

* gut everything (clear nvim)
* install packer following instruction here https://github.com/wbthomason/packer.nvim
* init.lua:

```lua
vim.o.termguicolors = true
vim.o.background = 'light'

return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use { 'ishan9299/nvim-solarized-lua',
  config = function()
	vim.g.solarized_diffmode = 'normal'
	vim.g.solarized_italics = 1
	vim.cmd('colorscheme solarized')
  end}
end)

-- this this a comment 
```

my apologies...
