### ISSUE TITLE
8 bit colors are very wrong

### ISSUE THREAD

**Issue by xPMo** [ishan9299/nvim-solarized-lua#36]
I use alacritty, which for some reason nvim doesn't pick up from the terminfo database, and so I got 8-bit colors. But the colors I got are not correct. [Your `convert.js`](https://gist.github.com/ishan9299/d87713b43dc04d49fa060711fdc7dd6d) does not use the correct formula:

![2021-12-23_23:43:50 Zoi](https://user-images.githubusercontent.com/16061366/147321367-05046f27-edc2-48a4-80d6-d34cdb6d765d.png)

The biggest problems here:

- No rounding each color to the nearest integer in [0-5]
- Missing the +16 offset to account for named colors (0-15)

New implementation (I changed the `console.log()` line to demo the truecolor as well):

```js
	let c8 = 16 + Math.floor(red*6/256)*36 + Math.floor(green*6/256)*6 + Math.floor(blue*6/256)
        // don't shoot me i'm not a js dev
	console.log("\x1b[38;2;" + red + ";" + green + ";" + blue + "m" + str + "\x1b[0m -> \x1b[38;5;" + c8 + "m" + c8);
```
![2021-12-24_00:05:41 9Dp](https://user-images.githubusercontent.com/16061366/147323047-4784b281-49e2-468f-a7ef-bb3fb9abfc91.png)

**Comment by ishan9299** [comment]
wow, thanks for the input can you send a pull request if possible?

**Comment by xPMo** [comment]
> wow, thanks for the input can you send a pull request if possible?

Yeah, I'll do that.
