### ISSUE TITLE
make TODOs pinkish and unclosed strings less garish

### ISSUE THREAD

**Issue by alok** [ishan9299/nvim-solarized-lua#4]
TODOs in comments are currently this horrible yellow color and unclosed strings hurt the eyes

<img width="628" alt="Screen Shot 2021-04-02 at 3 07 38 AM" src="https://user-images.githubusercontent.com/8325708/113406636-a9cf2300-9360-11eb-860e-9e9258c4b058.png">
<img width="368" alt="Screen Shot 2021-04-02 at 2 59 01 AM" src="https://user-images.githubusercontent.com/8325708/113406637-ab005000-9360-11eb-911f-075ccf45cfe1.png">

**Comment by ishan9299** [comment]
can you update the theme and check?

**Comment by ishan9299** [comment]
also can you check if the background is set to 'dark' or 'light'?

**Comment by alok** [comment]
the theme seems to get reset. investigating.

**Comment by ishan9299** [comment]
This usually happens when you set the background color after applying the color scheme. In vim/neovim there are default highlights for dark and light mode, so they will reset the highlights given by the theme.

**Comment by alok** [comment]
I don't have my background set to anything though. Maybe another plugin is messing with it?

**Comment by ishan9299** [comment]
Probably because TODO is pinkish on my neovim. Are you using vim-polyglot or something similar?
