### ISSUE TITLE
make comments grayed out

### ISSUE THREAD

**Issue by alok** [ishan9299/nvim-solarized-lua#5]
as opposed to being plain color

<img width="398" alt="Screen Shot 2021-04-02 at 3 14 55 AM" src="https://user-images.githubusercontent.com/8325708/113407150-9d979580-9361-11eb-9357-3633361af593.png">

**Comment by ishan9299** [comment]
There are other variants for solarized I have added not too long ago maybe try those. If you still have a problem with other variants then I guess will fix it.

**Comment by alok** [comment]
related to reset issue from before.
