### ISSUE TITLE
All highlighting stopped working with neovim 0.8

### ISSUE THREAD

**Issue by rbjorklin** [ishan9299/nvim-solarized-lua#52]
There seems to have been some breaking changes in the [new 0.8 release](https://github.com/neovim/neovim/releases/tag/v0.8.0).

**Comment by erikw** [comment]
When using nvim 0.8 + master on nvim-treesitter, highlights are not working anymore. It seems that all colorschemes needs to be updated.

See https://github.com/nvim-treesitter/nvim-treesitter/issues/3680

**Comment by rbjorklin** [comment]
Looks like the colorscheme is actually okay and the real problem is that filetype detection has stopped working. If I do `:set ft=ocaml` the highlighting works just fine.

**Comment by rbjorklin** [comment]
@erikw I fixed my highlighting issues by removing [these bits from my config](https://github.com/rbjorklin/set-me-up/commit/0e5bb6206507c1a3cbe2883879946046b7885dd1#diff-067d32de6dc1fe6f05ed472cbd402b9a928a52e8d15e42b00fafd70c51d94af6L1-L8). I have also tweaked the colorscheme a bit in #54, give it a spin and let me know what you think!

@ishan9299 any chance you could review and possibly merge this?

**Comment by Dieterbe** [comment]
@rbjorklin i'm glad i found your issue!
per the 0.7 announcement on the blog i had added these lines to my config:
```
-- new filetype part of 0.7: https://neovim.io/news/2022/04
vim.g.do_filetype_lua = 1
vim.g.did_load_filetypes = 0
```

your assesment is spot on, but also surprising, that the upgrade to v0.8 requires a removal of such config. i expected the transition from "opt-in" to "by default" be a bit smoother.
either way, thanks to dev team for all their hard work!
