### ISSUE TITLE
gutter too bright

### ISSUE THREAD

**Issue by alok** [ishan9299/nvim-solarized-lua#6]
<img width="133" alt="Screen Shot 2021-04-02 at 3 46 04 AM" src="https://user-images.githubusercontent.com/8325708/113409353-f406d300-9365-11eb-8b8a-fe0e4abda4c5.png">

**Comment by ishan9299** [comment]
are you using gitgutter from airblade? 
On my system they look like this:- 
![Screenshot from 2021-04-02 19-06-06](https://user-images.githubusercontent.com/47824004/113420235-96669b00-93e6-11eb-88c4-6c6c1a57cce7.png)

maybe try updating the colorscheme? If it doesn't work please let me know. I have added other variants of solarized like in vim-solarized8, so can you specify what variant are you using? If you still have the issue after updating.

**Comment by alok** [comment]
no, that's the sign for a warning (unused import i think). i don't use gitgutter
