### ISSUE TITLE
 lots of things are highlighted yellow

### ISSUE THREAD

**Issue by alok** [ishan9299/nvim-solarized-lua#7]
this goes against solarized being easy on the eyes. in lua, strings are highlighted yellow when i cursor over them using the standard lsp.

**Comment by ishan9299** [comment]
Do you have the backgroud set as dark after setting the colorscheme in you config?
There are only 23 highlight groups that yellow in solarized-normal
❯ grep -i yellow highlights.lua 
73:		syntax['DiffChange'] = {guifg=colors.yellow, guibg='none', guisp=colors.yellow, gui='none'}
78:		syntax['DiffChange'] = {guifg=colors.yellow, guibg='none', gui='reverse'}
83:		syntax['DiffChange'] = {guifg=colors.yellow,guibg=colors.base02,guisp=colors.yellow,gui='none'}
119:		syntax['SpellLocal'] = {guifg=colors.yellow,guibg=colors.base3,guisp=colors.orange,gui='undercurl'}
130:		syntax['SpellLocal'] = {guifg=colors.yellow,guibg='none',guisp=colors.yellow,gui='undercurl'}
141:		syntax['SpellLocal'] = {guifg=colors.yellow,guibg='none',guisp=colors.yellow,gui='undercurl'}
161:	syntax['Search'] = {guifg=colors.yellow,guibg='none',gui='reverse'}
177:	syntax['Type'] = {guifg=colors.yellow,guibg='none',gui='none'}
185:	syntax['vimCommand'] = {guifg=colors.yellow,guibg='none',gui='none'}
194:	syntax['vimSynMtchOpt'] = {guifg=colors.yellow,guibg='none',gui='none'}
209:	syntax['gitcommitUnmergedFile'] = {guifg=colors.yellow,guibg='none',gui='bold'}
217:	syntax['javaScript'] = {guifg=colors.yellow,guibg='none',gui='none'}
219:	syntax['perlVarPlain'] = {guifg=colors.yellow,guibg=colors.base03,gui='none'}
222:	syntax['texmathzonex'] = {guifg=colors.yellow,guibg=colors.base03,gui='none'}
223:	syntax['texmathmatcher'] = {guifg=colors.yellow,guibg=colors.base03,gui='none'}
224:	syntax['texreflabel'] = {guifg=colors.yellow,guibg=colors.base03,gui='none'}
229:	syntax['ConId'] = {guifg=colors.yellow,guibg='none',gui='none'}
236:	syntax['hs_OpFunctionName'] = {guifg=colors.yellow,guibg='none',gui='none'}
239:	syntax['hsType'] = {guifg=colors.yellow,guibg='none',gui='none'}
246:	syntax['pandocVerbatimBlock'] = {guifg=colors.yellow,guibg='none',gui='none'}
250:	syntax['pandocBlockQuoteLeader3'] = {guifg=colors.yellow,guibg='none',gui='none'}
316:	syntax['pandocVerbatimInline'] = {guifg=colors.yellow,guibg='none',gui='none'}
435:	syntax['LspDiagnosticsDefaultWarning'] = {guifg=colors.yellow,guibg='none',guisp=colors.yellow,gui='undercurl'}

**Comment by alok** [comment]
yes my background is dark. i think i just really hate yellow

**Comment by ishan9299** [comment]
In what file format are you getting yellow strings? Because strings are supposed to be #2aa198 color coded which is far from being yellow. Can paste an example text then it will be easier to fix it.
