### ISSUE TITLE
split marker is ugly

### ISSUE THREAD

**Issue by alok** [ishan9299/nvim-solarized-lua#8]
it's grey with dotted black line in between. is there something that gives a sort of smoother blend?

**Comment by ishan9299** [comment]
does typing the command `hi VertSplit guibg=#002b36` fix it for you?

**Comment by ishan9299** [comment]
Also try this :set fillchars+=vert:\

**Comment by ishan9299** [comment]
You can also set the solarized_statusline as flat and see if it fits your needs.
